name: cs3dash
channels:
  - dwr-cvm
  - cadwr-dms
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas=2.1.4
  - matplotlib=3.8.0
  - seaborn=0.12.2
  - plotly=5.9.0
  - bokeh=3.3.0
  - pyhecdss=1.3.0
  - pandss=0.6
  - calsim_objects=0.1
  - openpyxl=3.0.10
  - ipykernel=6.25.0
  - black=23.11.0
  - isort=5.9.3
  - flake8=6.1.0
  - tabulate=0.9.0
  - pint=0.23
  - tqdm=4.65.0
  - dash
  - dash-bootstrap-components==1.5.0
  - pip:
      - dash-uploader==0.0.6
